docker network connect pentest_network go_a11y_quick-app-1 || true
docker network connect pentest_network go_accessibility_score-app-1 || true
docker network connect pentest_network go_ad_density-app-1 || true
docker network connect pentest_network go_address_extractor-app-1 || true
docker network connect pentest_network go_api_first-app-1 || true
docker network connect pentest_network go_biz_classifier-app-1 || true
docker network connect pentest_network go_broken_links-app-1 || true
docker network connect pentest_network go_cas-app-1 || true
docker network connect pentest_network go_cognitive_load-app-1 || true
docker network connect pentest_network go_company_size-app-1 || true
docker network connect pentest_network go_currency_detector-app-1 || true
docker network connect pentest_network go_customer_logos-app-1 || true
docker network connect pentest_network go_data_inventory-app-1 || true
docker network connect pentest_network go_dependency_counter-app-1 || true
docker network connect pentest_network go_dtss-app-1 || true
docker network connect pentest_network go_email_extractor-app-1 || true
docker network connect pentest_network go_emotional_tone-app-1 || true
docker network connect pentest_network go_founding_year-app-1 || true
docker network connect pentest_network go_funding_detector-app-1 || true
docker network connect pentest_network go_gdpr_compliance-app-1 || true
docker network connect pentest_network go_keyword_density-app-1 || true
docker network connect pentest_network go_legal_entity-app-1 || true
docker network connect pentest_network go_mobile_friendly-app-1 || true
docker network connect pentest_network go_office_locations-app-1 || true
docker network connect pentest_network go_outlink_graph-app-1 || true
docker network connect pentest_network go_page_load_metrics-app-1 || true
docker network connect pentest_network go_payment_detector-app-1 || true
docker network connect pentest_network go_phone_extractor-app-1 || true
docker network connect pentest_network go_press_mentions-app-1 || true
docker network connect pentest_network go_price_range-app-1 || true
docker network connect pentest_network go_remote_detector-app-1 || true
docker network connect pentest_network go_revenue_model-app-1 || true
docker network connect pentest_network go_robots_parser-app-1 || true
docker network connect pentest_network go_scc-app-1 || true
docker network connect pentest_network go_seasonal_detector-app-1 || true
docker network connect pentest_network go_security_headers-app-1 || true
docker network connect pentest_network go_seo_basics-app-1 || true
docker network connect pentest_network go_services_dashboard-app-1 || true
docker network connect pentest_network go_shipping_regions-app-1 || true
docker network connect pentest_network go_sitemap_finder-app-1 || true
docker network connect pentest_network go_social_graph-app-1 || true
docker network connect pentest_network go_svi-app-1 || true
docker network connect pentest_network go_team_size-app-1 || true
docker network connect pentest_network go_technology_stack-app-1 || true
docker network connect pentest_network go_tos_finder-app-1 || true
docker network connect pentest_network go_trust_decay-app-1 || true
docker network connect pentest_network go_ugc_detector-app-1 || true
docker network connect pentest_network go_update_frequency-app-1 || true
docker network connect pentest_network go_wps-app-1 || true
docker network connect pentest_network go_xss_scanner-app-1 || true
docker network connect pentest_network go_apikey_scanner-app-1 || true
docker network connect pentest_network go_clickjacking_tester-app-1 || true
docker network connect pentest_network go_cookie_checker-app-1 || true
docker network connect pentest_network go_cors_scanner-app-1 || true
docker network connect pentest_network go_cors_tester-app-1 || true
docker network connect pentest_network go_crlf_tester-app-1 || true
docker network connect pentest_network go_debug_detector-app-1 || true
docker network connect pentest_network go_graphql_introspection-app-1 || true
docker network connect pentest_network go_host_header-app-1 || true
docker network connect pentest_network go_idor_finder-app-1 || true
docker network connect pentest_network go_iframe_analyzer-app-1 || true
docker network connect pentest_network go_jsonp_finder-app-1 || true
docker network connect pentest_network go_mime_trap-app-1 || true
docker network connect pentest_network go_open_redirect-app-1 || true
docker network connect pentest_network go_ratelimit_tester-app-1 || true
docker network connect pentest_network go_secrets_scanner-app-1 || true
docker network connect pentest_network go_smuggling_probe-app-1 || true
docker network connect pentest_network go_subdomain_takeover-app-1 || true
docker network connect pentest_network go_xss_payload-app-1 || true
docker network connect pentest_network go_zone_transfer-app-1 || true
docker network connect pentest_network go_admin_finder-app-1 || true
docker network connect pentest_network go_api_extractor-app-1 || true
docker network connect pentest_network go_asn_lookup-app-1 || true
docker network connect pentest_network go_blocklist_checker-app-1 || true
docker network connect pentest_network go_bucket_finder-app-1 || true
docker network connect pentest_network go_comment_extractor-app-1 || true
docker network connect pentest_network go_crypto_finder-app-1 || true
docker network connect pentest_network go_dir_listing-app-1 || true
docker network connect pentest_network go_email_harvester-app-1 || true
docker network connect pentest_network go_env_finder-app-1 || true
docker network connect pentest_network go_hidden_fields-app-1 || true
docker network connect pentest_network go_phone_extractor-app-1 || true
docker network connect pentest_network go_sourcemap_finder-app-1 || true
docker network connect pentest_network go_subdomain_finder-app-1 || true
docker network connect pentest_network go_swagger_finder-app-1 || true
docker network connect pentest_network go_typosquat_finder-app-1 || true
docker network connect pentest_network go_wayback_checker-app-1 || true
docker network connect pentest_network go_wellknown_scanner-app-1 || true
docker network connect pentest_network go_wp_plugins-app-1 || true
docker network connect pentest_network go_caa_checker-app-1 || true
docker network connect pentest_network go_cdn_detector-app-1 || true
docker network connect pentest_network go_compression_tester-app-1 || true
docker network connect pentest_network go_hsts_checker-app-1 || true
docker network connect pentest_network go_http_protocol-app-1 || true
docker network connect pentest_network go_ipv6_checker-app-1 || true
docker network connect pentest_network go_loadbalancer_detect-app-1 || true
docker network connect pentest_network go_oauth_mapper-app-1 || true
docker network connect pentest_network go_proxy_fingerprint-app-1 || true
docker network connect pentest_network go_redirect_tracer-app-1 || true
docker network connect pentest_network go_reverse_dns-app-1 || true
docker network connect pentest_network go_websocket_analyzer-app-1 || true
docker network connect pentest_network go_broken_links-app-1 || true
docker network connect pentest_network go_captcha_detector-app-1 || true
docker network connect pentest_network go_feed_finder-app-1 || true
docker network connect pentest_network go_jwt_debugger-app-1 || true
docker network connect pentest_network go_login_analyzer-app-1 || true
docker network connect pentest_network go_pwa_manifest-app-1 || true
docker network connect pentest_network go_robots_analyzer-app-1 || true
docker network connect pentest_network go_schema_extractor-app-1 || true
docker network connect pentest_network go_security_txt-app-1 || true
docker network connect pentest_network go_tech_stack-app-1 || true
docker network connect pentest_network go-html-proxy || true
docker network connect pentest_network go-search-duck-go || true
